/**
 * Deterministic, fact-derived explanations (Parts 18 and 8.8 of the
 * real-device remediation brief).
 *
 * Every sentence produced here is built from a value the user actually
 * persisted during onboarding, or from a decision the server-side engine
 * actually recorded. Nothing is generated by a language model, and nothing
 * says "chosen based on your preferences" unless the listed preference was
 * genuinely part of the selection.
 */
import type { ProgrammeStructure } from '@/domain/programme/structure';

const DAY_LABELS: Record<string, string> = {
  monday: 'Mon',
  tuesday: 'Tue',
  wednesday: 'Wed',
  thursday: 'Thu',
  friday: 'Fri',
  saturday: 'Sat',
  sunday: 'Sun',
};

export function formatTrainingDays(days: string[]): string {
  return days.map((day) => DAY_LABELS[day.toLowerCase()] ?? day).join(', ');
}

const EQUIPMENT_LABELS: Record<string, string> = {
  bodyweight: 'bodyweight only',
  dumbbell: 'dumbbells',
  barbell: 'a barbell',
  kettlebell: 'a kettlebell',
  bench: 'a bench',
  pull_up_bar: 'a pull-up bar',
  resistance_band: 'resistance bands',
  cable_machine: 'a cable machine',
  leg_press_machine: 'a leg press machine',
  lat_pulldown_machine: 'a lat pulldown machine',
};

export function formatEquipmentKeys(keys: string[]): string {
  const labels = keys.map((key) => EQUIPMENT_LABELS[key] ?? key.replace(/_/g, ' '));
  if (labels.length === 0) return '';
  if (labels.length === 1) return labels[0];
  return `${labels.slice(0, -1).join(', ')} and ${labels[labels.length - 1]}`;
}

/** True when the only equipment recorded is the no-equipment sentinel. */
export function isBodyweightOnly(equipmentKeys: string[]): boolean {
  return equipmentKeys.length > 0 && equipmentKeys.every((key) => key === 'bodyweight');
}

/**
 * "Why this plan?" — one bullet per real input the engine used. Returns an
 * empty list when the version predates exercise selection, so the screen
 * can say so instead of implying reasoning that never happened.
 */
export function describePlanRationale(structure: ProgrammeStructure): string[] {
  const reasons: string[] = [];

  if (structure.goalPriorities.length > 0) {
    const [primary, ...rest] = structure.goalPriorities;
    reasons.push(
      rest.length > 0
        ? `Your top goal is ${primary.label.toLowerCase()}, followed by ${rest
            .map((goal) => goal.label.toLowerCase())
            .join(', ')}.`
        : `Your goal is ${primary.label.toLowerCase()}.`,
    );
  }

  if (structure.trainingDays.length > 0) {
    reasons.push(
      `You said you can train ${structure.trainingDays.length} ${
        structure.trainingDays.length === 1 ? 'day' : 'days'
      } a week: ${formatTrainingDays(structure.trainingDays)}.`,
    );
  }

  if (structure.sessionDurationMinutes) {
    reasons.push(`Each session is sized to fit about ${structure.sessionDurationMinutes} minutes.`);
  }

  if (structure.equipmentKeys.length > 0) {
    reasons.push(
      isBodyweightOnly(structure.equipmentKeys)
        ? 'You train without equipment, so every exercise here needs none.'
        : `You have ${formatEquipmentKeys(structure.equipmentKeys)}, so exercise choice is limited to what that covers.`,
    );
  }

  if (structure.requiresClearance) {
    reasons.push(
      'Your safety answers mean higher-risk content is held back until you have confirmed with a qualified professional.',
    );
  }

  return reasons;
}
