/**
 * Generated database types for the Murphy Method Supabase schema.
 *
 * Source of truth: supabase/migrations/*.sql. Generated by introspecting a
 * local PostgreSQL 16 instance with every Phase 2A migration applied
 * (scripts/local-pg-harness — see docs/SUPABASE_SETUP.md), since the
 * Docker-dependent `supabase gen types --local`/`--db-url` path cannot run
 * in this sandbox. Regenerate with the real command once Docker/a linked
 * project is available:
 *
 *   supabase gen types typescript --local > src/types/database.ts
 *
 * Do not hand-edit table shapes here without also updating the migration
 * that defines them — this file must always describe the actual schema,
 * never a second, independently-maintained representation of it.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: string;
          profile_id: string | null;
          event_type: string;
          actor: 'user' | 'system' | 'admin';
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          event_type: string;
          actor: 'user' | 'system' | 'admin';
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          event_type?: string;
          actor?: 'user' | 'system' | 'admin';
          metadata?: Json;
          created_at?: string;
        };
        Relationships: [];
      };
      body_area_goals: {
        Row: {
          id: string;
          profile_id: string;
          body_area_key:
            | 'shoulders'
            | 'chest'
            | 'biceps'
            | 'triceps'
            | 'forearms'
            | 'upper_back'
            | 'lats'
            | 'core'
            | 'waist_appearance'
            | 'glutes'
            | 'quadriceps'
            | 'hamstrings'
            | 'calves';
          priority: number | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          body_area_key:
            | 'shoulders'
            | 'chest'
            | 'biceps'
            | 'triceps'
            | 'forearms'
            | 'upper_back'
            | 'lats'
            | 'core'
            | 'waist_appearance'
            | 'glutes'
            | 'quadriceps'
            | 'hamstrings'
            | 'calves';
          priority?: number | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          body_area_key?:
            | 'shoulders'
            | 'chest'
            | 'biceps'
            | 'triceps'
            | 'forearms'
            | 'upper_back'
            | 'lats'
            | 'core'
            | 'waist_appearance'
            | 'glutes'
            | 'quadriceps'
            | 'hamstrings'
            | 'calves';
          priority?: number | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      body_area_muscle_map: {
        Row: {
          id: string;
          body_area_key: string;
          muscle_id: string;
          weight: number;
        };
        Insert: {
          id?: string;
          body_area_key: string;
          muscle_id: string;
          weight: number;
        };
        Update: {
          id?: string;
          body_area_key?: string;
          muscle_id?: string;
          weight?: number;
        };
        Relationships: [];
      };
      body_measurements: {
        Row: {
          id: string;
          profile_id: string;
          measured_on: string;
          metric: 'weight' | 'waist' | 'chest' | 'hips' | 'arm' | 'thigh' | 'calf';
          value: number;
          source: 'manual' | 'bodyscan_derived';
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          measured_on: string;
          metric: 'weight' | 'waist' | 'chest' | 'hips' | 'arm' | 'thigh' | 'calf';
          value: number;
          source?: 'manual' | 'bodyscan_derived';
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          measured_on?: string;
          metric?: 'weight' | 'waist' | 'chest' | 'hips' | 'arm' | 'thigh' | 'calf';
          value?: number;
          source?: 'manual' | 'bodyscan_derived';
          created_at?: string;
        };
        Relationships: [];
      };
      body_scan_images: {
        Row: {
          id: string;
          body_scan_id: string;
          angle: 'front' | 'side' | 'back' | 'angle_45';
          storage_path: string;
          capture_metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          body_scan_id: string;
          angle: 'front' | 'side' | 'back' | 'angle_45';
          storage_path: string;
          capture_metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          body_scan_id?: string;
          angle?: 'front' | 'side' | 'back' | 'angle_45';
          storage_path?: string;
          capture_metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      body_scans: {
        Row: {
          id: string;
          profile_id: string;
          captured_on: string;
          purpose: 'baseline' | 'progress_check';
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          captured_on: string;
          purpose: 'baseline' | 'progress_check';
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          captured_on?: string;
          purpose?: 'baseline' | 'progress_check';
          created_at?: string;
        };
        Relationships: [];
      };
      coach_messages: {
        Row: {
          id: string;
          thread_id: string;
          role: 'user' | 'assistant' | 'system_context';
          content: string;
          structured_context_snapshot: Json | null;
          model_version: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          thread_id: string;
          role: 'user' | 'assistant' | 'system_context';
          content: string;
          structured_context_snapshot?: Json | null;
          model_version?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          thread_id?: string;
          role?: 'user' | 'assistant' | 'system_context';
          content?: string;
          structured_context_snapshot?: Json | null;
          model_version?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      coach_threads: {
        Row: {
          id: string;
          profile_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      consent_records: {
        Row: {
          id: string;
          profile_id: string;
          consent_type:
            'bodyscan_capture' | 'bodyscan_ai_processing' | 'data_processing' | 'marketing';
          granted: boolean;
          version: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          consent_type:
            'bodyscan_capture' | 'bodyscan_ai_processing' | 'data_processing' | 'marketing';
          granted: boolean;
          version: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          consent_type?:
            'bodyscan_capture' | 'bodyscan_ai_processing' | 'data_processing' | 'marketing';
          granted?: boolean;
          version?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      decision_evidence: {
        Row: {
          id: string;
          decision_id: string;
          evidence_type:
            | 'exercise_feedback'
            | 'workout_feedback'
            | 'pain_report'
            | 'adherence_pattern'
            | 'performance_trend'
            | 'readiness_trend';
          source_table: string;
          source_id: string | null;
          weight: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          decision_id: string;
          evidence_type:
            | 'exercise_feedback'
            | 'workout_feedback'
            | 'pain_report'
            | 'adherence_pattern'
            | 'performance_trend'
            | 'readiness_trend';
          source_table: string;
          source_id?: string | null;
          weight: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          decision_id?: string;
          evidence_type?:
            | 'exercise_feedback'
            | 'workout_feedback'
            | 'pain_report'
            | 'adherence_pattern'
            | 'performance_trend'
            | 'readiness_trend';
          source_table?: string;
          source_id?: string | null;
          weight?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      equipment: {
        Row: {
          id: string;
          key: string;
          label: string;
          category: 'free_weight' | 'machine' | 'bodyweight' | 'accessory';
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          category: 'free_weight' | 'machine' | 'bodyweight' | 'accessory';
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          category?: 'free_weight' | 'machine' | 'bodyweight' | 'accessory';
        };
        Relationships: [];
      };
      exercise_equipment: {
        Row: {
          id: string;
          exercise_id: string;
          equipment_id: string;
          required: boolean;
        };
        Insert: {
          id?: string;
          exercise_id: string;
          equipment_id: string;
          required: boolean;
        };
        Update: {
          id?: string;
          exercise_id?: string;
          equipment_id?: string;
          required?: boolean;
        };
        Relationships: [];
      };
      exercise_feedback: {
        Row: {
          id: string;
          workout_exercise_id: string;
          enjoyment: number | null;
          difficulty: 'too_easy' | 'appropriate' | 'very_hard' | 'too_hard' | null;
          signal_type:
            'dislike' | 'excessive_difficulty' | 'pain' | 'technical_insecurity' | 'boredom' | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workout_exercise_id: string;
          enjoyment?: number | null;
          difficulty?: 'too_easy' | 'appropriate' | 'very_hard' | 'too_hard' | null;
          signal_type?:
            'dislike' | 'excessive_difficulty' | 'pain' | 'technical_insecurity' | 'boredom' | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workout_exercise_id?: string;
          enjoyment?: number | null;
          difficulty?: 'too_easy' | 'appropriate' | 'very_hard' | 'too_hard' | null;
          signal_type?:
            'dislike' | 'excessive_difficulty' | 'pain' | 'technical_insecurity' | 'boredom' | null;
          created_at?: string;
        };
        Relationships: [];
      };
      exercise_muscles: {
        Row: {
          id: string;
          exercise_id: string;
          muscle_id: string;
          role: 'primary' | 'secondary';
        };
        Insert: {
          id?: string;
          exercise_id: string;
          muscle_id: string;
          role: 'primary' | 'secondary';
        };
        Update: {
          id?: string;
          exercise_id?: string;
          muscle_id?: string;
          role?: 'primary' | 'secondary';
        };
        Relationships: [];
      };
      exercise_restrictions: {
        Row: {
          id: string;
          exercise_id: string;
          restriction_code: string;
          effect: 'exclude' | 'modify';
          notes: string | null;
        };
        Insert: {
          id?: string;
          exercise_id: string;
          restriction_code: string;
          effect: 'exclude' | 'modify';
          notes?: string | null;
        };
        Update: {
          id?: string;
          exercise_id?: string;
          restriction_code?: string;
          effect?: 'exclude' | 'modify';
          notes?: string | null;
        };
        Relationships: [];
      };
      exercise_substitutions: {
        Row: {
          id: string;
          exercise_id: string;
          substitute_exercise_id: string;
          similarity_score: number;
        };
        Insert: {
          id?: string;
          exercise_id: string;
          substitute_exercise_id: string;
          similarity_score: number;
        };
        Update: {
          id?: string;
          exercise_id?: string;
          substitute_exercise_id?: string;
          similarity_score?: number;
        };
        Relationships: [];
      };
      exercises: {
        Row: {
          id: string;
          name: string;
          slug: string;
          aliases: string[];
          description: string | null;
          movement_pattern_id: string;
          skill_requirement: 'low' | 'moderate' | 'high';
          difficulty: 'beginner' | 'intermediate' | 'advanced';
          stability_requirement: 'low' | 'moderate' | 'high';
          loading_potential: 'low' | 'moderate' | 'high';
          fatigue_profile: 'low' | 'moderate' | 'high';
          recommended_rep_range_low: number;
          recommended_rep_range_high: number;
          setup_time_seconds: number | null;
          media_url: string | null;
          content_version: string;
          dataset_version: string;
          source: 'internal_authoring' | 'licensed_dataset_import' | 'content_partner';
          review_status: 'draft' | 'reviewed' | 'published';
          reviewed_at: string | null;
          contraindication_metadata_version: string;
          locale_ready: boolean;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          aliases?: string[];
          description?: string | null;
          movement_pattern_id: string;
          skill_requirement: 'low' | 'moderate' | 'high';
          difficulty: 'beginner' | 'intermediate' | 'advanced';
          stability_requirement: 'low' | 'moderate' | 'high';
          loading_potential: 'low' | 'moderate' | 'high';
          fatigue_profile: 'low' | 'moderate' | 'high';
          recommended_rep_range_low: number;
          recommended_rep_range_high: number;
          setup_time_seconds?: number | null;
          media_url?: string | null;
          content_version?: string;
          dataset_version?: string;
          source: 'internal_authoring' | 'licensed_dataset_import' | 'content_partner';
          review_status?: 'draft' | 'reviewed' | 'published';
          reviewed_at?: string | null;
          contraindication_metadata_version?: string;
          locale_ready?: boolean;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          aliases?: string[];
          description?: string | null;
          movement_pattern_id?: string;
          skill_requirement?: 'low' | 'moderate' | 'high';
          difficulty?: 'beginner' | 'intermediate' | 'advanced';
          stability_requirement?: 'low' | 'moderate' | 'high';
          loading_potential?: 'low' | 'moderate' | 'high';
          fatigue_profile?: 'low' | 'moderate' | 'high';
          recommended_rep_range_low?: number;
          recommended_rep_range_high?: number;
          setup_time_seconds?: number | null;
          media_url?: string | null;
          content_version?: string;
          dataset_version?: string;
          source?: 'internal_authoring' | 'licensed_dataset_import' | 'content_partner';
          review_status?: 'draft' | 'reviewed' | 'published';
          reviewed_at?: string | null;
          contraindication_metadata_version?: string;
          locale_ready?: boolean;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      goals: {
        Row: {
          id: string;
          key: string;
          label: string;
          description: string | null;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          description?: string | null;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          description?: string | null;
        };
        Relationships: [];
      };
      health_screenings: {
        Row: {
          id: string;
          profile_id: string;
          responses: Json;
          screening_version: string;
          requires_clearance: boolean;
          restriction_flags: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          responses: Json;
          screening_version: string;
          requires_clearance?: boolean;
          restriction_flags?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          responses?: Json;
          screening_version?: string;
          requires_clearance?: boolean;
          restriction_flags?: string[];
          created_at?: string;
        };
        Relationships: [];
      };
      motivation_profiles: {
        Row: {
          id: string;
          profile_id: string;
          numerical_target_responsiveness: number | null;
          encouragement_responsiveness: number | null;
          pr_responsiveness: number | null;
          time_minimisation_responsiveness: number | null;
          competitive_framing_responsiveness: number | null;
          preferred_notification_time: string | null;
          streak_pressure_averse: boolean | null;
          notification_fatigue_score: number | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          numerical_target_responsiveness?: number | null;
          encouragement_responsiveness?: number | null;
          pr_responsiveness?: number | null;
          time_minimisation_responsiveness?: number | null;
          competitive_framing_responsiveness?: number | null;
          preferred_notification_time?: string | null;
          streak_pressure_averse?: boolean | null;
          notification_fatigue_score?: number | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          numerical_target_responsiveness?: number | null;
          encouragement_responsiveness?: number | null;
          pr_responsiveness?: number | null;
          time_minimisation_responsiveness?: number | null;
          competitive_framing_responsiveness?: number | null;
          preferred_notification_time?: string | null;
          streak_pressure_averse?: boolean | null;
          notification_fatigue_score?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      movement_patterns: {
        Row: {
          id: string;
          key: string;
          label: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
        };
        Relationships: [];
      };
      muscles: {
        Row: {
          id: string;
          key: string;
          label: string;
          muscle_group: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          muscle_group: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          muscle_group?: string;
        };
        Relationships: [];
      };
      notification_preferences: {
        Row: {
          id: string;
          profile_id: string;
          workout_reminders_enabled: boolean;
          missed_start_nudges_enabled: boolean;
          progress_notifications_enabled: boolean;
          bodyscan_reminders_enabled: boolean;
          quiet_hours_start: string | null;
          quiet_hours_end: string | null;
          preferred_reminder_time: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          workout_reminders_enabled?: boolean;
          missed_start_nudges_enabled?: boolean;
          progress_notifications_enabled?: boolean;
          bodyscan_reminders_enabled?: boolean;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          preferred_reminder_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          workout_reminders_enabled?: boolean;
          missed_start_nudges_enabled?: boolean;
          progress_notifications_enabled?: boolean;
          bodyscan_reminders_enabled?: boolean;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          preferred_reminder_time?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      notification_responses: {
        Row: {
          id: string;
          notification_id: string;
          response_type:
            'opened' | 'started_workout' | 'quick' | 'rescheduled' | 'skipped' | 'dismissed';
          responded_at: string;
        };
        Insert: {
          id?: string;
          notification_id: string;
          response_type:
            'opened' | 'started_workout' | 'quick' | 'rescheduled' | 'skipped' | 'dismissed';
          responded_at?: string;
        };
        Update: {
          id?: string;
          notification_id?: string;
          response_type?:
            'opened' | 'started_workout' | 'quick' | 'rescheduled' | 'skipped' | 'dismissed';
          responded_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          profile_id: string;
          notification_type: 'workout_reminder' | 'missed_start' | 'progress' | 'bodyscan_due';
          payload: Json;
          scheduled_for: string;
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          notification_type: 'workout_reminder' | 'missed_start' | 'progress' | 'bodyscan_due';
          payload: Json;
          scheduled_for: string;
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          notification_type?: 'workout_reminder' | 'missed_start' | 'progress' | 'bodyscan_due';
          payload?: Json;
          scheduled_for?: string;
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pain_reports: {
        Row: {
          id: string;
          profile_id: string;
          workout_exercise_id: string | null;
          exercise_id: string | null;
          body_area: string;
          severity: 'mild' | 'moderate' | 'significant';
          description: string | null;
          action_taken:
            'paused_progression' | 'exercise_modified' | 'exercise_stopped' | 'escalation_shown';
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          workout_exercise_id?: string | null;
          exercise_id?: string | null;
          body_area: string;
          severity: 'mild' | 'moderate' | 'significant';
          description?: string | null;
          action_taken:
            'paused_progression' | 'exercise_modified' | 'exercise_stopped' | 'escalation_shown';
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          workout_exercise_id?: string | null;
          exercise_id?: string | null;
          body_area?: string;
          severity?: 'mild' | 'moderate' | 'significant';
          description?: string | null;
          action_taken?:
            'paused_progression' | 'exercise_modified' | 'exercise_stopped' | 'escalation_shown';
          created_at?: string;
        };
        Relationships: [];
      };
      performance_metrics: {
        Row: {
          id: string;
          profile_id: string;
          exercise_id: string | null;
          metric_type: string;
          period_start: string;
          period_end: string;
          value: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          exercise_id?: string | null;
          metric_type: string;
          period_start: string;
          period_end: string;
          value: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          exercise_id?: string | null;
          metric_type?: string;
          period_start?: string;
          period_end?: string;
          value?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      personal_records: {
        Row: {
          id: string;
          profile_id: string;
          exercise_id: string;
          record_type: 'max_weight' | 'max_reps_at_weight' | 'estimated_1rm';
          value: number;
          set_log_id: string | null;
          achieved_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          exercise_id: string;
          record_type: 'max_weight' | 'max_reps_at_weight' | 'estimated_1rm';
          value: number;
          set_log_id?: string | null;
          achieved_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          exercise_id?: string;
          record_type?: 'max_weight' | 'max_reps_at_weight' | 'estimated_1rm';
          value?: number;
          set_log_id?: string | null;
          achieved_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      personal_response_models: {
        Row: {
          id: string;
          profile_id: string;
          domain: 'physical' | 'training' | 'preference' | 'behavioural' | 'motivation';
          attribute_key: string;
          estimate: Json;
          confidence: number;
          evidence_count: number;
          personalisation_rules_version: string;
          last_updated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          domain: 'physical' | 'training' | 'preference' | 'behavioural' | 'motivation';
          attribute_key: string;
          estimate: Json;
          confidence: number;
          evidence_count?: number;
          personalisation_rules_version: string;
          last_updated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          domain?: 'physical' | 'training' | 'preference' | 'behavioural' | 'motivation';
          attribute_key?: string;
          estimate?: Json;
          confidence?: number;
          evidence_count?: number;
          personalisation_rules_version?: string;
          last_updated_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      preference_signals: {
        Row: {
          id: string;
          profile_id: string;
          signal_type: string;
          subject_id: string | null;
          value: Json;
          source_table: string;
          source_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          signal_type: string;
          subject_id?: string | null;
          value: Json;
          source_table: string;
          source_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          signal_type?: string;
          subject_id?: string | null;
          value?: Json;
          source_table?: string;
          source_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          date_of_birth: string | null;
          biological_sex: string | null;
          height_cm: number | null;
          unit_preference: 'metric' | 'imperial';
          training_experience: 'beginner' | 'recreational' | 'intermediate' | null;
          available_training_days: string[] | null;
          preferred_session_duration_minutes: number | null;
          coaching_style:
            'supportive' | 'direct' | 'analytical' | 'competitive' | 'calm_minimal' | null;
          onboarding_completed_at: string | null;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          date_of_birth?: string | null;
          biological_sex?: string | null;
          height_cm?: number | null;
          unit_preference?: 'metric' | 'imperial';
          training_experience?: 'beginner' | 'recreational' | 'intermediate' | null;
          available_training_days?: string[] | null;
          preferred_session_duration_minutes?: number | null;
          coaching_style?:
            'supportive' | 'direct' | 'analytical' | 'competitive' | 'calm_minimal' | null;
          onboarding_completed_at?: string | null;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          date_of_birth?: string | null;
          biological_sex?: string | null;
          height_cm?: number | null;
          unit_preference?: 'metric' | 'imperial';
          training_experience?: 'beginner' | 'recreational' | 'intermediate' | null;
          available_training_days?: string[] | null;
          preferred_session_duration_minutes?: number | null;
          coaching_style?:
            'supportive' | 'direct' | 'analytical' | 'competitive' | 'calm_minimal' | null;
          onboarding_completed_at?: string | null;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      programme_decisions: {
        Row: {
          id: string;
          profile_id: string;
          change_level: 0 | 1 | 2 | 3 | 4;
          decision_type:
            | 'load_progression'
            | 'exercise_substitution'
            | 'deload'
            | 'programme_restructure'
            | 'user_requested_change';
          summary: string;
          confidence: number | null;
          triggered_by: 'system' | 'user';
          outcome: 'applied' | 'abstained';
          engine_version: string;
          safety_rules_version: string;
          personalisation_rules_version: string | null;
          evidence_engine_version: string | null;
          llm_model_version: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          change_level: 0 | 1 | 2 | 3 | 4;
          decision_type:
            | 'load_progression'
            | 'exercise_substitution'
            | 'deload'
            | 'programme_restructure'
            | 'user_requested_change';
          summary: string;
          confidence?: number | null;
          triggered_by: 'system' | 'user';
          outcome: 'applied' | 'abstained';
          engine_version: string;
          safety_rules_version: string;
          personalisation_rules_version?: string | null;
          evidence_engine_version?: string | null;
          llm_model_version?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          change_level?: 0 | 1 | 2 | 3 | 4;
          decision_type?:
            | 'load_progression'
            | 'exercise_substitution'
            | 'deload'
            | 'programme_restructure'
            | 'user_requested_change';
          summary?: string;
          confidence?: number | null;
          triggered_by?: 'system' | 'user';
          outcome?: 'applied' | 'abstained';
          engine_version?: string;
          safety_rules_version?: string;
          personalisation_rules_version?: string | null;
          evidence_engine_version?: string | null;
          llm_model_version?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      programme_versions: {
        Row: {
          id: string;
          programme_id: string;
          previous_version_id: string | null;
          version_number: number;
          structure: Json;
          change_level: 0 | 1 | 2 | 3 | 4;
          change_reason: string;
          decision_id: string | null;
          engine_version: string;
          exercise_dataset_version: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          programme_id: string;
          previous_version_id?: string | null;
          version_number: number;
          structure: Json;
          change_level: 0 | 1 | 2 | 3 | 4;
          change_reason: string;
          decision_id?: string | null;
          engine_version: string;
          exercise_dataset_version: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          programme_id?: string;
          previous_version_id?: string | null;
          version_number?: number;
          structure?: Json;
          change_level?: 0 | 1 | 2 | 3 | 4;
          change_reason?: string;
          decision_id?: string | null;
          engine_version?: string;
          exercise_dataset_version?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      programmes: {
        Row: {
          id: string;
          profile_id: string;
          status: 'active' | 'paused' | 'archived';
          current_version_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          status?: 'active' | 'paused' | 'archived';
          current_version_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          status?: 'active' | 'paused' | 'archived';
          current_version_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      readiness_entries: {
        Row: {
          id: string;
          profile_id: string;
          entry_date: string;
          readiness: 'very_low' | 'low' | 'normal' | 'good' | 'excellent';
          sleep_quality: number | null;
          soreness: number | null;
          available_minutes: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          entry_date: string;
          readiness: 'very_low' | 'low' | 'normal' | 'good' | 'excellent';
          sleep_quality?: number | null;
          soreness?: number | null;
          available_minutes?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          entry_date?: string;
          readiness?: 'very_low' | 'low' | 'normal' | 'good' | 'excellent';
          sleep_quality?: number | null;
          soreness?: number | null;
          available_minutes?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      scan_quality: {
        Row: {
          id: string;
          body_scan_image_id: string;
          reliability: 'high' | 'moderate' | 'low';
          factors: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          body_scan_image_id: string;
          reliability: 'high' | 'moderate' | 'low';
          factors?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          body_scan_image_id?: string;
          reliability?: 'high' | 'moderate' | 'low';
          factors?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      set_logs: {
        Row: {
          id: string;
          workout_exercise_id: string;
          set_number: number;
          weight_kg: number | null;
          reps: number;
          effort_response: number | null;
          completed_at: string;
          client_generated_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workout_exercise_id: string;
          set_number: number;
          weight_kg?: number | null;
          reps: number;
          effort_response?: number | null;
          completed_at?: string;
          client_generated_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workout_exercise_id?: string;
          set_number?: number;
          weight_kg?: number | null;
          reps?: number;
          effort_response?: number | null;
          completed_at?: string;
          client_generated_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          profile_id: string;
          tier: 'free' | 'premium' | 'premium_plus';
          status: 'active' | 'trialing' | 'past_due' | 'cancelled';
          provider: string | null;
          provider_reference: string | null;
          current_period_end: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          tier?: 'free' | 'premium' | 'premium_plus';
          status?: 'active' | 'trialing' | 'past_due' | 'cancelled';
          provider?: string | null;
          provider_reference?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          tier?: 'free' | 'premium' | 'premium_plus';
          status?: 'active' | 'trialing' | 'past_due' | 'cancelled';
          provider?: string | null;
          provider_reference?: string | null;
          current_period_end?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      training_blocks: {
        Row: {
          id: string;
          programme_version_id: string;
          block_number: number;
          starts_on: string;
          ends_on: string | null;
          focus_summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          programme_version_id: string;
          block_number: number;
          starts_on: string;
          ends_on?: string | null;
          focus_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          programme_version_id?: string;
          block_number?: number;
          starts_on?: string;
          ends_on?: string | null;
          focus_summary?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      user_equipment: {
        Row: {
          id: string;
          profile_id: string;
          equipment_id: string;
          available: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          equipment_id: string;
          available?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          equipment_id?: string;
          available?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_goals: {
        Row: {
          id: string;
          profile_id: string;
          goal_id: string;
          priority: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          goal_id: string;
          priority: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          goal_id?: string;
          priority?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workout_exercises: {
        Row: {
          id: string;
          workout_id: string;
          exercise_id: string;
          order_index: number;
          target_sets: number;
          target_rep_range_low: number;
          target_rep_range_high: number;
          suggested_load_kg: number | null;
          substituted_from_exercise_id: string | null;
          client_generated_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workout_id: string;
          exercise_id: string;
          order_index: number;
          target_sets: number;
          target_rep_range_low: number;
          target_rep_range_high: number;
          suggested_load_kg?: number | null;
          substituted_from_exercise_id?: string | null;
          client_generated_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workout_id?: string;
          exercise_id?: string;
          order_index?: number;
          target_sets?: number;
          target_rep_range_low?: number;
          target_rep_range_high?: number;
          suggested_load_kg?: number | null;
          substituted_from_exercise_id?: string | null;
          client_generated_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      workout_feedback: {
        Row: {
          id: string;
          workout_id: string;
          enjoyment: number | null;
          overall_difficulty: number | null;
          energy_afterwards: 'better' | 'same' | 'worse' | null;
          would_repeat: 'yes' | 'maybe' | 'no' | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workout_id: string;
          enjoyment?: number | null;
          overall_difficulty?: number | null;
          energy_afterwards?: 'better' | 'same' | 'worse' | null;
          would_repeat?: 'yes' | 'maybe' | 'no' | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workout_id?: string;
          enjoyment?: number | null;
          overall_difficulty?: number | null;
          energy_afterwards?: 'better' | 'same' | 'worse' | null;
          would_repeat?: 'yes' | 'maybe' | 'no' | null;
          created_at?: string;
        };
        Relationships: [];
      };
      workouts: {
        Row: {
          id: string;
          profile_id: string;
          programme_version_id: string | null;
          training_block_id: string | null;
          mode: 'full' | 'quick' | 'minimum';
          status: 'planned' | 'in_progress' | 'completed' | 'skipped';
          scheduled_for: string | null;
          started_at: string | null;
          completed_at: string | null;
          estimated_duration_minutes: number | null;
          client_generated_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          programme_version_id?: string | null;
          training_block_id?: string | null;
          mode: 'full' | 'quick' | 'minimum';
          status?: 'planned' | 'in_progress' | 'completed' | 'skipped';
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          estimated_duration_minutes?: number | null;
          client_generated_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          programme_version_id?: string | null;
          training_block_id?: string | null;
          mode?: 'full' | 'quick' | 'minimum';
          status?: 'planned' | 'in_progress' | 'completed' | 'skipped';
          scheduled_for?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          estimated_duration_minutes?: number | null;
          client_generated_id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
